@startmindmap
'https://plantuml.com/mindmap-diagram

caption figure 1
title My super title

* <&flag>Debian
** <&globe>Ubuntu
*** Linux Mint
*** Kubuntu
*** Lubuntu
*** KDE Neon
** <&graph>LMDE
** <&pulse>SolydXK
** <&people>SteamOS
** <&star>Raspbian with a very long name
*** <s>Raspmbc</s> => OSMC
*** <s>Raspyfi</s> => Volumio

header
My super header
endheader

center footer My super footer

legend right
  Short
  legend
endlegend
@endmindmap


@startmindmap
* 干货面试题
** 计算机网络面试题
*** TCP/IP十五连问
*** 两万字计算机面试题汇总
** MySQL面试题
** Redis面试题
** 大厂面试真题
*** 虾皮十五连问
*** 五年Oppo后端面试真题
*** 腾讯云十五连问
@endmindmap

@startmindmap
* 表结构
** 去除定制表 商户+频道+工会唯一索引 改为联合索引
** 定制表、日志表新增规则开始时间 结束时间 字段
** 定制表、日志表新增时间规则生效方式字段

* 定制服务费后台
** 原始数据默认长期生效
** 新增
 *** 根据商户+频道+工会查询所有数据
 *** 校验数据不能大于5条
 *** 校验时间范围不能交叉
 *** 配置时间生效规则为指定时间区间生效时检验开始时间和结束时间为必填
 *** 存在指定时间区间生效时不允许添加长期生效规则
** 编辑
   *** 限制商户、频道、工会不可编辑
   *** 根据商户+频道+工会查询所有数据
   *** 校验数据不能大于5条
   *** 校验时间范围不能交叉
   *** 配置时间生效规则为指定时间区间生效时检验开始时间和结束时间为必填
   *** 存在指定时间区间生效时不允许添加长期生效规则 
    ** 启用
       *** 根据商户+频道+工会查询所有数据
       *** 校验该规则如果启用是否会导致配置数据出现时间交叉，如果会，则不允许启用
     ** 复制
     *** 限制商户、频道、工会不可编辑
     *** 根据商户+频道+工会查询所有数据
     *** 校验数据不能大于5条
     *** 校验时间范围不能交叉
     *** 配置时间生效规则为指定时间区间生效时检验开始时间和结束时间为必填
     *** 存在指定时间区间生效时不允许添加长期生效规则     
       ** 列表
       *** 返回时间信息
       
* 查询接口
  ** 计算服务覅额接口
    *** 根据当前时间查询服务费
    *** 根据时间匹配对应的规则
    *** 如果当前时间没有对应的规则则走通用配置
    *** 如果存在相应的配置并且是生效中
       **** 配置不收取服务费 则没有服务费
       **** 收取返回相应的服务费
    *** 计算相应的服务费   

  ** 查询服务费配置接口
    *** 根据当前时间查询服务费
    *** 根据时间匹配对应的规则
    *** 如果当前时间没有对应的规则则走通用配置
    
    *** 查询定制规则
          ****    查询定制为空，走通用
            ****   查询定制不为空但是没有命中任何一个，走通用
             ****  查询定制不为空命中其中一条但是这条数据是禁用的，走通用
             ****  查询定制不为空命中其中一条这条数据是启用的支持收取服务费，则收服务费
              **** 查询定制不为空命中其中一条这条数据是启用的但是不支持收取服务费，则收服务费
    
    
    *** 如果存在相应的配置并且是生效中
       **** 配置不收取服务费 则没有服务费
       **** 收取返回相应的服务费

  ** 用户授权接口
   ***  保持现有逻辑不做修改
       
       
       
       




@endmindmap



@startmindmap
* 查询接口：
  ** 计算服务覅额接口：
    *** 根据当前时间查询服务费
    *** 根据时间匹配对应的规则
    *** 如果当前时间没有对应的规则则走通用配置
    *** 如果存在相应的配置并且是生效中：
       **** 配置不收取服务费 则没有服务费
       **** 收取返回相应的服务费
    *** 计算相应的服务费   

  ** 查询服务费配置接口：
    *** 根据当前时间查询服务费
    *** 根据时间匹配对应的规则
    *** 如果当前时间没有对应的规则则走通用配置
    *** 如果存在相应的配置并且是生效中：
       **** 配置不收取服务费 则没有服务费
       **** 收取返回相应的服务费

  ** 用户授权接口
   ***  根据商户+频道查询 当前时间 生效中的所有数据，只要有一条是启用则收服务费
   *** 查询数据为空 则走通用的         
 @endmindmap 

@startmindmap
* 查询接口
  ** 计算服务覅额接口：
    *** 根据当前时间查询服务费
    *** 根据时间匹配对应的规则
    *** 如果当前时间没有对应的规则则走通用配置
    *** 如果存在相应的配置并且是生效中：
       **** 配置不收取服务费 则没有服务费
       **** 收取返回相应的服务费
    *** 计算相应的服务费   

  ** 查询服务费配置接口：
    *** 根据当前时间查询服务费
    *** 根据时间匹配对应的规则
    *** 如果当前时间没有对应的规则则走通用配置
    *** 如果存在相应的配置并且是生效中：
       **** 配置不收取服务费 则没有服务费
       **** 收取返回相应的服务费

  ** 用户授权接口
   ***  根据商户+频道查询 当前时间 生效中的所有数据，只要有一条是启用则收服务费
   *** 查询数据为空 则走通用的         
 @endmindmap 
 
 @startmindmap
 * 订单详情
   ** 订单基础数据查询 
   ** 订单商品信息查询
   ** 券码信息查询
     *** 生成二维码
     *** 券码核销状态
   ** 订单支付信息查询
   ** 商家预约信息查询
     *** 是否预约商家
     *** 商家联系电话
   ** 项目信息查询
    ***  活动地点信息
   **  是否展示 退款 按钮逻辑      
   **  是否展示 去支付 按钮逻辑      
      *** 待支付金额计算
   **  是否展示 删除订单 按钮逻辑         
  @endmindmap     
  
   @startmindmap
   * 支付回调
     ** 支付超时
       *** 订单状态已取消 
     ** 根据单支浩获取订单数据
     ** 订单支付信息落库
     ** 是否预约成团
       *** 是
         **** 通知供应链出券
         ***** 记录券信息落库
         **** 通知履约
       *** 否
         **** 订单状态待确认
     ** 发短信  
    @endmindmap   
    
      @startmindmap
       * 订单供应链交互信息
         ** 查库存
           
         ** 冻结库存
         ** 还库存
         ** 支付成功出券接口
         ** 预约成团出券接口
          
         ** 券核销通知订单  
         ** 券核过期知订单  
         ** 券订单退款->通知供应链
        @endmindmap  
        
        
         @startmindmap
               * 订单成团
                 ** 供应链获取券信息
                 ** 券信息落库更新
                 ** 更新订单状态
                 ** 发短信  
                @endmindmap   